id: 'seq-1'
################
# RNN SETTINGS #
################
# size of inputs EXCLUDING any autoregressive functionality. So 129 (pitches) + 1 (onset) + 1 (offset).
input_size: 131
# choose between 'onehot', 'scalar', and 'none'
autoregressive_type: 'onehot'
# seq_type: type of RNN
seq_type: 'GRU'
# size of hidden state
hidden_size: 300
# number of layers in the RNN
num_layers: 1
# dropout probability for RNN
dropout: 0.0
# is bidirectional?
bidirectional: False

###################
# LINEAR SETTINGS #
###################
num_linears: 1
linear_hidden_size: 100